#!/bin/bash

# Uses downforeveryoneorjustme.com to check if a specified website is up or down
# Quick & dirty implementation
# Author: @m4gu5

address=$1

curl http://downforeveryoneorjustme.com/$address | grep "It's just you." >/dev/null

if [ $? == 0 ]
then
        # It's just you
	echo "1"
else
        # It's not just you
	echo "0"
        exit 1
fi
