#!/bin/sh

# Author: @m4gu5
# License: GPL
# This script sets the current "Astronomic Picture Of The Day" as wallpaper in Gnome.
# If you use feh or another program to set your desktop wallpaper you have to change the last line of this script.


if [ "$#" -ne 1 ]
# If path was not specified, save in /tmp/
then
    path="/tmp/"
else
    path=$1
    if [ "$S" != */ ]
    # If directory does not end with a /, add it
    then
        path="$path/"
    fi
fi

url="http://apod.nasa.gov/apod/"
# Get the url of the actual image
imageurl=$url$(curl $url | grep '<a href="image/' | cut -d "\"" -f2 | cut -d "\"" -f1)
absoluteFilename=$path$(basename $imageurl)

if ! [ -f $absoluteFilename ]
# If picture was not already downloaded
then
    wget $imageurl -P $path
    if [ "$?" -ne 0 ]
    then
        echo "APOD cannot be downloaded. Please check your internet connection."
        exit 1
    fi
fi

# Sets the desktop wallpaper
# Change this command if you use another program to set the wallpaper
gsettings set org.gnome.desktop.background picture-uri file://$absoluteFilename
